name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Download Godot lib 
      run: curl https://downloads.tuxfamily.org/godotengine/4.0/alpha13/godot-lib.4.0.alpha13.release.aar -o "godot-lib.aar"

    - name: Move Godot lib to libs path
      run: mv ./godot-lib.aar  Godot-Android-Ads-Plugin/libs/

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: GodotAndroidAds.aar
        path: Godot-Android-Ads-Plugin/build/outputs/aar/
        retention-days: 7
